### ISSUE TITLE
garbage_collector cannot list all objects.

### ISSUE THREAD

**Issue by liyan-ah** [influxdata/influxdb3_core#17]
Refered from [aws-ListObjectsV2](https://docs.aws.amazon.com/zh_cn/AmazonS3/latest/API/API_ListObjectsV2.html) and [azure-List Blobs](https://learn.microsoft.com/en-us/rest/api/storageservices/list-blobs?tabs=microsoft-entra-id), `object_store.List(None)` can only return 1_000 and 5_000 objects respectively.

**Comment by philjb** [comment]
Hi @liyan-ah - the underlying `object_store` crate handles pagination (via continuation_tokens for s3 and markers via azure): check it out: https://docs.rs/object_store/latest/object_store/trait.ObjectStore.html#tymethod.list
