### ISSUE TITLE
CacheSystem::RefreshPolicy may never refresh: It's a feature or a bug ?

### ISSUE THREAD

**Issue by liyan-ah** [influxdata/influxdb3_core#30]
If `get()` called, and if `state.running_refresh.is_none()`, a new `t_next` is generated and put back to `timings`.

https://github.com/influxdata/influxdb3_core/blob/1da8f733200431c21b2b002cdf46545a205d3b0f/cache_system/src/backend/policy/refresh.rs#L380-L402

But if `t_next` is set and `t_next` > `time_provider.now()`, the `t_next`'s reset would make `refresh` task delayed. And if get is always being called, the refresh_policy may never works.

https://github.com/influxdata/influxdb3_core/blob/1da8f733200431c21b2b002cdf46545a205d3b0f/cache_system/src/backend/policy/refresh.rs#L269-L282

To make it clear, consider there is only k1, and the `state.backoff_cfg` set to 10s. 

```
T+00s       set(k1, v1, now) was called. k1's refresh task is scheduled. And no `get()`. t_next set to T+10s.
T+10s        k1 is refreshed. And t_next set to T+20s. From now, `get()` would be called every 1 second.
T+11s        get(k1), t_next = T+21s.
T+12s        get(k1), t_next = T+22s.
T+13s       get(k1), t_next = T+23s.
...
```
k1 would never be refreshed until get() stops being called.

**Comment by hiltontj** [comment]
Hi @liyan-ah - we realized that the `cache_system` crate is no longer used and will be removing it in #31. Thank you for raising this issue, though, that is a good catch.
